---
name: pxc

releases:
  - name: pxc
    version: latest
  - name: bpm
    version: latest

addons:
  - name: bpm
    jobs:
      - name: bpm
        release: bpm

instance_groups:
  - name: mysql
    instances: 1
    azs: [z1, z2, z3]
    networks: [{name: default}]
    vm_type: default
    stemcell: default
    persistent_disk: 10000
    jobs:
      - name: pxc-mysql
        release: pxc
        properties:
          admin_password: ((cf_mysql_mysql_admin_password))
          tls:
            galera: ((galera_server_certificate))
            server: ((mysql_server_certificate))
          seeded_users:
            smoke-tests-user:
              role: schema-admin
              schema: pxc_release_test_db
              password: ((smoke_tests_db_password))
              host: any
      - name: smoke-tests
        release: pxc
        properties:
          db_password: ((smoke_tests_db_password))

stemcells:
  - alias: default
    os: ubuntu-jammy
    version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000
  serial: false

variables:
  - name: cf_mysql_mysql_admin_password
    type: password
  - name: pxc_galera_ca
    type: certificate
    options:
      is_ca: true
      common_name: pxc_galera_ca
  - name: pxc_server_ca
    type: certificate
    options:
      is_ca: true
      common_name: pxc_server_ca
  - name: galera_server_certificate
    type: certificate
    options:
      ca: pxc_galera_ca
      extended_key_usage: [ "server_auth", "client_auth" ]
      common_name: galera_server_certificate
  - name: mysql_server_certificate
    type: certificate
    options:
      ca: pxc_server_ca
      common_name: mysql_server_certificate
  - name: smoke_tests_db_password
    type: password
