#!/usr/bin/env bash

set -o errexit -o nounset -o xtrace

: "${MYSQL_ENGINE:="pxc-8.0"}"
: "${MYSQL_ENGINE_VERSION:=latest}"
: "${DEPLOYMENT_NAME:=${MYSQL_ENGINE%-8.0}-backup}"
: "${STEMCELL:=ubuntu-jammy}"

declare -a engine_deploy_args

case "${MYSQL_ENGINE}" in
pxc)
  engine_deploy_args+=(
    --ops-file=operations/pxc/add-pxc.yml
    --ops-file=operations/pxc/use-clustered.yml
    --ops-file=operations/pxc/add-smoke-tests-user-job.yml
    --ops-file=operations/backup-from-inactive-node.yml
    --ops-file=operations/pxc/enable-remote-admin-access.yml
    --ops-file=operations/pxc/galera-agent-tls.yml
  )
  ;;
pxc-8.0)
  engine_deploy_args+=(
    --ops-file=operations/pxc/add-pxc.yml
    --ops-file=operations/pxc/use-pxc80.yml
    --ops-file=operations/pxc/use-clustered.yml
    --ops-file=operations/pxc/seeded-users.yml
    --ops-file=operations/backup-from-inactive-node.yml
    --ops-file=operations/pxc/enable-remote-admin-access.yml
    --ops-file=operations/pxc/galera-agent-tls.yml
  )
  ;;
dedicated-mysql)
  engine_deploy_args+=(--ops-file=operations/dmr/add-dmr.yml)
  ;;
*)
  echo >&2 "Unknown ENGINE=$MYSQL_ENGINE"
  exit 1
  ;;
esac

bosh deploy --no-redact --non-interactive \
  operations/mysql_with_backup.yml \
  --ops-file=operations/create-dev-release.yml \
  --deployment="${DEPLOYMENT_NAME}" \
  --ops-file=operations/deployment-name.yml \
  --var=deployment_name="${DEPLOYMENT_NAME}" \
  --ops-file=operations/engine-version.yml \
  --var=engine="${MYSQL_ENGINE%-8.0}" \
  --var=engine_version="${MYSQL_ENGINE_VERSION}" \
  --ops-file=operations/stemcell.yml \
  --var=stemcell_os="${STEMCELL}" \
  --ops-file=operations/use-mtls.yml \
  "${engine_deploy_args[@]}" \
  "$@"
