#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

RELEASE_DIR="$( cd $MY_DIR/.. && pwd )"

source ${RELEASE_DIR}/.envrc

echo -e "\nTesting Streaming backup tool..."
${RELEASE_DIR}/src/streaming-mysql-backup-tool/bin/test "$@"

echo -e "\nTesting Streaming backup client..."
${RELEASE_DIR}/src/streaming-mysql-backup-client/bin/test "$@"

pushd ${RELEASE_DIR}/spec
  bundle install
  bundle exec rspec ./
popd
