#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

RELEASE_DIR="$( cd $MY_DIR/.. && pwd )"

source ${RELEASE_DIR}/.envrc

# Remove and reinstall the ginkgo binary as it might be from the wrong target architecture
rm -rf ${RELEASE_DIR}/bin/ginkgo
rm -rf ${RELEASE_DIR}/bin/fgt

go install github.com/onsi/ginkgo/ginkgo@latest
go install github.com/GeertJohan/fgt@latest
go install github.com/maxbrunsfeld/counterfeiter/v6

echo -e "\nTesting Streaming backup tool..."
${RELEASE_DIR}/src/streaming-mysql-backup-tool/bin/test "$@"

echo -e "\nTesting Streaming backup client..."
${RELEASE_DIR}/src/streaming-mysql-backup-client/bin/test "$@"

pushd ${RELEASE_DIR}/spec
  bundle install
  bundle exec rspec ./
popd
